# config
logo: /images/svdb.png
keywords: "iseongho, front end, back end, developer, development"
menu:
  Home: /
  Articles: /articles
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
