# config
logo: /images/svdb.png
keywords: "iseongho, front end, back end, developer"
menu:
  Home: /
  Github: https://github.com/iseongho

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss2.xml
google_analytics:
